#!/bin/bash                                                                     

tr -cs "[\-A-Za-z0-9.,'/\!]" '[\n*]' | sort -u | comm -23 - sorted.words | tr -cs 'A-Za-z' '[\n*]' | sort -u | comm -23 - sorted.words

